### ISSUE TITLE
CloneLab throws a TypeError when an expired GitLab access token is used

### ISSUE THREAD

**Issue by naiveHobo** [Chaitanya-git/CloneLab#1]
Traceback (most recent call last):
  File "/home/naivehobo/.local/bin/clonelab", line 109, in <module>
    main(sys.argv[1:])
  File "/home/naivehobo/.local/bin/clonelab", line 98, in main
    group = get_group(base_url, token_segment, search_string)
  File "/home/naivehobo/.local/bin/clonelab", line 28, in get_group
    print("\t" + str(i) + ') '  + result['web_url'])
TypeError: string indices must be integers

**Comment by Chaitanya-git** [comment]
Fixed in 889e09d
